### PR TITLE
Added DoD

### PR DESCRIPTION
**Pull request by ViktorIsenborg**

### CODE REVIEW

**Review by ViktorIsenborg — COMMENTED** [review]
:)

**Review by ChristofferLjungAhlstedt — CHANGES_REQUESTED** [review]
No good, make more expressive. Review code line by line sounds abit not very nice. We will have loads of shit libs and such and i wont read it

**Review by ViktorIsenborg — COMMENTED** [review]
DoD is a bit more expressive now.

**Review by ChristofferLjungAhlstedt — CHANGES_REQUESTED** [review]
You know what has to be changed.   "add preferably comments to a function that is not directly clear." ?? This is unclear
It needs to run for it to be in main branch not "if possible"
I don't need permission tp push my code. It's the pulls that matter
We are not using post-it notes

**Review by ViktorIsenborg — COMMENTED** [review]
Followed up on comment

**Review by ChristofferLjungAhlstedt — CHANGES_REQUESTED** [review]
Code should not be in main the main branch if it does not run or know has errors in it. To ensure this, all code that will be pulled to main shall pass a pull request

**Review by ViktorIsenborg — COMMENTED** [review]
Let's hope this works

**Review by ChristofferLjungAhlstedt — APPROVED** [review]

**Review by AlbinNosskire — APPROVED** [review]

**Pull request merged**
